import { mockIPC } from "@tauri-apps/api/mocks";
import { DEFAULT_SETTINGS, type AppSettings } from "@/features/settings/lib/app-settings";
import type { AppStateWire } from "@/features/project/stores/project-store";
import type { Theme, ThemeSummary } from "@/features/theme/lib/theme-api";
import builtinThemesJson from "./builtin-themes.json";

const builtinThemes: Theme[] = builtinThemesJson as Theme[];
let settings: AppSettings = { ...DEFAULT_SETTINGS };
let generation = 0;

function themeSummaries(): ThemeSummary[] {
  return builtinThemes.map((theme) => ({
    id: theme.id,
    name: theme.name,
    author: theme.author,
    license: theme.license,
    hasDark: Boolean(theme.dark),
    hasLight: Boolean(theme.light),
    builtIn: true,
    warnings: theme.warnings ?? [],
  }));
}

const bootstrap = (): AppStateWire => ({
  currentProject: null,
  recentProjects: [],
  workspaces: [],
  groups: [],
  activeWorkspaceId: null,
  organisations: [],
  activeOrganisationId: null,
  settings,
  configGeneration: generation,
  configStatus: { status: "ok" },
  version: 4,
});

/** Browser-only Tauri adapter. Theme JSON is generated by the atlas-theme
 *  crate; `cargo test -p atlas-theme` fails if this snapshot is stale. */
export function installMockBackend(): void {
  mockIPC((command, args) => {
    switch (command) {
      case "list_themes":
        return themeSummaries();
      case "get_theme": {
        const id = (args as { id?: string }).id;
        const theme = builtinThemes.find((candidate) => candidate.id === id);
        if (!theme) throw new Error(`theme '${id}' was not found`);
        return theme;
      }
      case "bootstrap_app_state":
        return bootstrap();
      case "cli_take_initial_project_path":
        return null;
      case "update_atlas_settings": {
        const patch = (args as { patch: Partial<AppSettings> }).patch;
        settings = { ...settings, ...patch };
        generation += 1;
        return { kind: "applied", settings, generation };
      }
      case "reset_atlas_config":
        settings = { ...DEFAULT_SETTINGS };
        generation += 1;
        return { settings, generation };
      default:
        return null;
    }
  });
}
